name: ESLint
on: [push, pull_request]
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v2
        
      - name: Install Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i eslint eslint-config-hardcore

      - name: Run ESLint
        run: npx eslint ./src --ext .ts --quiet 
